# Generated by Django 3.2.9 on 2021-11-21 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Default'), (2, 'Report')], default=1)),
                ('total_like', models.IntegerField(default=0, editable=False)),
                ('total_comment', models.IntegerField(default=0, editable=False)),
                ('total_view', models.IntegerField(default=0, editable=False)),
                ('status', models.IntegerField(choices=[(0, 'InActive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'forum_post',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'forum_post_like',
            },
        ),
        migrations.CreateModel(
            name='ForumPostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='forum/picture/')),
                ('status', models.IntegerField(choices=[(0, 'InActive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'forum_post_picture',
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('total_like', models.IntegerField(default=0, editable=False)),
                ('total_comment', models.IntegerField(default=0, editable=False)),
                ('status', models.IntegerField(choices=[(0, 'InActive'), (1, 'Active')], default=1)),
            ],
            options={
                'db_table': 'forum_thread',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ForumThreadLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_thread_like', to='forum.forumthread')),
            ],
            options={
                'db_table': 'forum_thread_like',
            },
        ),
    ]
