# Generated by Django 3.2.9 on 2021-11-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Reported'), (2, 'Solved')], default=1)),
                ('flood_status', models.IntegerField(choices=[(1, 'Safe'), (2, 'Warning'), (3, 'Danger')], default=1)),
                ('flood_depth', models.FloatField(blank=True, null=True)),
                ('is_user_report', models.BooleanField()),
                ('is_system_report', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_lat_long_mapping', to='location.location')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
