# Generated by Django 3.2.9 on 2021-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20211121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercurrent',
            name='clouds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='dt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='ground_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='rain_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='rain_3h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='sea_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='sunrise',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='sunset',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='temp_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='timezone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='wind_deg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercurrent',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
